name: biomad_frontend
description: BioMad application to control your health
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^2.1.0
  openapi_generator_annotations: ^1.0.8
  cupertino_icons: ^1.0.0
  dio: ^3.0.9
  api:
    path: ./api
  easy_localization: ^2.3.3
  flutter_redux: ^0.7.0
  redux: ^4.0.0+3
  localstorage: ^3.0.3+6
  redux_thunk: ^0.3.0
  sliding_up_panel: ^1.0.2
  datetime_picker_formfield: ^1.0.0
  flutter_svg: ^0.19.1
  google_sign_in: ^4.5.6
  flutter_facebook_login: ^3.0.0
  flutter_login_vk: ^0.2.0
  devicelocale: ^0.3.3
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  openapi_generator: ^1.1.0
  build_runner: '>=1.3.0 <=1.10.3'
  flutter_launcher_icons: '^0.8.0'

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/en.json
    - assets/translations/ru.json
    - assets/svg/fb_logo.svg
    - assets/svg/vk_logo.svg
    - assets/svg/google_logo.svg