name: biomad_frontend
description: BioMad application to control your health
publish_to: 'none'

version: 1.0.0+7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  openapi_generator_annotations: ^3.2.1
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  api:
    path: ./api
  easy_localization: ^3.0.0
  flutter_redux: ^0.8.2
  redux: ^5.0.0
  localstorage: ^4.0.0+1
  redux_thunk: ^0.4.0
  sliding_up_panel: ^2.0.0+1
  datetime_picker_formfield: ^2.0.0
  flutter_svg: ^0.22.0
  google_sign_in: ^5.1.1
  flutter_login_vk: ^2.1.0
  devicelocale: ^0.5.0
  url_launcher: ^6.0.12
  flutter_datetime_picker: ^1.5.1
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  openapi_generator: ^3.2.1
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/en.json
    - assets/translations/ru.json
    - assets/svg/fb_logo.svg
    - assets/svg/vk_logo.svg
    - assets/svg/google_logo.svg